### ISSUE TITLE
This is amazing!

### ISSUE THREAD

**Issue by notflip** [Serpentarius13/reusable-modal#1]
Thank you! I've been looking for a reusable component for a long time now.
Quick question, If I have an action that is being called from the Modal, such as creating a user, and I want the modal to close after that, should I call the modalStore from the userStore and clear the component there? Or how would you achieve this?

**Comment by Serpentarius13** [comment]
@notflip Hey, thank you! I suppose you would instantiate userStore and modalStore in your modal component and use their functions. Pinia actually allows calling one store inside the other, so its up to you
